CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS media (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), filename text NOT NULL, mime_type text NOT NULL, bytes bytea NOT NULL, size integer NOT NULL, width integer NOT NULL, height integer NOT NULL, alt text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS news (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), slug text NOT NULL UNIQUE, title text NOT NULL, excerpt text NOT NULL, content jsonb NOT NULL, cover_id uuid REFERENCES media(id) ON DELETE SET NULL, published boolean NOT NULL DEFAULT false, published_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS projects (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), slug text NOT NULL UNIQUE, title text NOT NULL, category text NOT NULL, location text NOT NULL, description text NOT NULL, developer text, facade_area numeric(12,2), floors text, sections text, status text NOT NULL DEFAULT 'В процессе', published boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS project_media (project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE, media_id uuid NOT NULL REFERENCES media(id) ON DELETE CASCADE, position integer NOT NULL DEFAULT 0, PRIMARY KEY(project_id,media_id));
CREATE TABLE IF NOT EXISTS audit_log (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), actor_email text NOT NULL, action text NOT NULL, entity_type text NOT NULL, entity_id uuid, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS admin_login_attempts (key text PRIMARY KEY, failed_count integer NOT NULL DEFAULT 0, window_started_at timestamptz NOT NULL DEFAULT now(), blocked_until timestamptz, updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS news_publication_idx ON news(published,published_at DESC);
CREATE INDEX IF NOT EXISTS projects_publication_idx ON projects(published,created_at DESC);
