import Link from "next/link";
import { desc } from "drizzle-orm";
import { signOut } from "@/auth";
import { requireAdmin } from "@/src/shared/lib/admin";
import { db } from "@/src/shared/lib/db";
import { galleryAlbums, newsItems, projectsTable } from "@/src/shared/lib/db/schema";
import { deleteEntry, togglePublished } from "./actions";
export const dynamic = "force-dynamic";
export default async function AdminPage() { const user = await requireAdmin(); const [news, projects, gallery] = await Promise.all([db().select({id:newsItems.id,title:newsItems.title,published:newsItems.published}).from(newsItems).orderBy(desc(newsItems.createdAt)), db().select({id:projectsTable.id,title:projectsTable.title,published:projectsTable.published}).from(projectsTable).orderBy(desc(projectsTable.createdAt)), db().select({id:galleryAlbums.id,title:galleryAlbums.title,published:galleryAlbums.published}).from(galleryAlbums).orderBy(desc(galleryAlbums.year))]); return <main className="admin-shell"><header><div><span>FS / ADMIN</span><strong>{user.name}</strong></div><form action={async()=>{"use server";await signOut({redirectTo:"/"})}}><button className="admin-ghost">Выйти</button></form></header><section className="admin-heading"><div><p>Управление контентом</p><h1>Публикации</h1></div></section><AdminList title="Новости" type="news" items={news}/><AdminList title="Объекты" type="project" items={projects}/><AdminList title="Галерея" type="gallery" items={gallery}/></main>; }
function AdminList({title,type,items}:{title:string;type:"news"|"project"|"gallery";items:{id:string;title:string;published:boolean}[]}) { const segment=type==="news"?"news":type==="project"?"projects":"gallery";return <section className="admin-list"><div className="admin-list-heading"><h2>{title}</h2><Link href={`/admin/${segment}/new`} aria-label={`Добавить: ${title}`} title={`Добавить: ${title}`}>+</Link></div>{items.length===0?<p className="admin-empty">Пока ничего нет</p>:items.map(item=><article key={item.id}><span className={item.published?"is-live":""}>{item.published?"Опубликовано":"Черновик"}</span><Link className="admin-item-title" href={`/admin/${segment}/${item.id}`}>{item.title}</Link><div className="admin-item-actions"><Link href={`/admin/${segment}/${item.id}`}>Открыть</Link><form action={togglePublished}><input type="hidden" name="id" value={item.id}/><input type="hidden" name="type" value={type}/><input type="hidden" name="published" value={String(!item.published)}/><button className="admin-publish">{item.published?"Снять с публикации":"Опубликовать"}</button></form><form action={deleteEntry}><input type="hidden" name="id" value={item.id}/><input type="hidden" name="type" value={type}/><button className="admin-delete">Удалить</button></form></div></article>)}</section>; }
